# -*- coding: utf-8 -*-
"""day25_functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uEIWaoDNiR9melUA8EtftjrSqPq2qUaI
"""

def violation(latency):
  if latency>200.0:
    return "BREACH"
  else:
    return "COMPLAINT"
print(violation(145.2))
print(violation(204.8))

def bonus(salary):
  amount=salary*0.15
  return amount
total_amount=bonus(80000)
print(total_amount)